FROM node:20-alpine

WORKDIR /usr/src/app

# Enable pnpm via corepack
RUN corepack enable

# Copy workspace files
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN pnpm install --frozen-lockfile

# Generate Prisma client
RUN pnpm run db:generate

# Build project
RUN pnpm run build

CMD ["pnpm", "run", "start-user-app"]
